sudo: required

services:
  - docker

script:
  - docker build -t t08094a/ionic .
  - docker run t08094a/ionic /bin/sh -c "ionic -v && ionic config set -g backend legacy && ionic start test blank --no-link --no-git --cordova && cd test && ionic cordova platform add android --no-resources && ionic cordova build android"
  